### ISSUE TITLE
calibrate IMU

### ISSUE THREAD

**Issue by fatemeh-mohseni-AI** [adolfos94/ROS-Stereo-Camera#2]
hello . 
I've launched the camera with its IMU and I can have IMU data by running the << ICM20948_Demo >> file  . 
but it does not give correct data when it is rotated or shaken and I think it needs calibration .
now how can i calibrate it to fetch the real data of the IMU and how can i import the IMU data into my python code ?
 I would appreciate it if you would help me with it.

**Comment by fatemeh-mohseni-AI** [comment]
sorry ! I know how to use IMU data in ROS . I just need your help with calibrating it . thanks

**Comment by adolfos94** [comment]
Did you try this: https://github.com/adolfos94/Stereo-Calibration ?

You need a chess board in order to calibrate the cameras!
